### PR TITLE
Skip specified .SSDs

### PR DESCRIPTION
**Pull request by lurkio**
We've found that some of the games on Mick's DSDs need special handling and can't just be automatically processed onto individual per-game .SSDs by the script, so I've created a [skiplist](https://github.com/lurkio/split_md_dsd/blob/master/ssd-skiplist.txt), which the script will read in if it's present, and which contains a list of .SSDs that the script should NOT output. (For bbcmicro.co.uk we've then manually created and uploaded our own custom versions of the games on the skiplist.) You may wish to ignore all this.

Also incorporated your recent catalogue-full error-handling.

### CODE REVIEW

**Comment by sweharris** [comment]
What special casing is necessary for these?  If we can determine programmatically what should be done then this would be better for repeatability, so the tree can be rebuilt from source at any time.

I just tried 023-ChuckieEgg2 and it seems to load OK in BeebEm... so I'm not sure what is needed to be done.

**Comment by sweharris** [comment]
Also there's no way I can merge your pull request without bringing in stuff like `Disc134.dsd` which is wrong.  For small changes I can manually cut'n'paste but as your fork gets more and more out of sync with my copy then things will get harder.

Normally you would create a branch for each set of changes, but when I'm making changes to other people's code I tend to delete my fork and create a new one each time just to be safe :-)

**Comment by lurkio** [comment]
Some of the reasons for skipping certain .SSDs are (poorly) documented here:

https://docs.google.com/spreadsheets/d/1EqNWKad0j3OCpLk7aSSMQZbTUTyEyQ1g2PRbtt2t7fU/edit?usp=sharing

It's all quite complicated, and I can't keep track of it all in my head. And, as I said, you may wish to ignore it all altogether.

But the reason I thought we might want to sync up is so that if you make any changes to the script in future they'll be easy for me to merge in to my fork. I've now deleted the DSD from my repository. I've also deleted the sample skiplist. So you might feel more inclined to accept a new Pull Request, which I can open. Or not.

**Comment by sweharris** [comment]
(I didn't see ChuckieEgg2 on that list, so I'm still a little confused.  But never mind :-))

So I'm gonna suggest three alternate solutions:

1. Call the `split_md_dsd.pl` program from a shell script, and afterwards just `rm` the files you don't care about.  This would result in a tree that's identical.  Since the split program is so fast, it may only be 1 second or so difference in speed

2. Call the split program and then copy over replacement SSDs on top of the newly extracted ones.

3. Make the "ignore" list optional (defaults to none) requiring a flag (eg `split_md_dsd.pl -i myignorelist`).

My gut feeling would be number 2 (or maybe a variation of number 1) to avoid having lists of files coded into config files, and running the risk of them getting out of date.

**Comment by lurkio** [comment]
Re option 3, the skiplist is already optional: if it's not present, the script will still work, and it _won't_ skip the creation of any .SSDs.

**Comment by sweharris** [comment]
OK, so this prompted me to make a few changes in CLI handling; source and results directories are now changable via options (`-S` and `-R`), and you can also specify a specific list of DSDs to process (rather than all).  I've also added a variation of your skiplist code (`--skipfile`).  

This should be a lot more flexible for testing, for updating single DSDs (eg when a fix is made to Disc023) and for comparison purposes.   It _should_ be backwards compatible; let me know if it causes problems!

**Pull request closed without merging**
